### ISSUE TITLE
Fix sfincs executable

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#135]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

test_hazard_run.py failing

### Current behaviour

pointing to the wrong sfincs executable

### Desired behaviour

pointing to the sfincs executable without a folder layer with the sfincs version

### Task list

- [ ] move code from main to env_fix into the new function
