### ISSUE TITLE
Fix risk map calculation

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#137]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

def test_rp_floodmap_calculation():
    test_toml = (
        test_database
        / "charleston"
        / "input"
        / "scenarios"
        / "current_test_set_no_measures"
        / "current_test_set_no_measures.toml"
    )

    assert test_toml.is_file()

    # use event template to get the associated Event child class
    test_scenario = Scenario.load_file(test_toml)
    test_scenario.init_object_model()
    test_scenario.direct_impacts.hazard.calculate_rp_floodmaps()
    nc_file = (
        test_database
        / "charleston"
        / "output"
        / "simulations"
        / "current_test_set_no_measures"
        / "rp_water_level.nc"
    )
    assert nc_file.is_file()
    zs_file1 = (
        test_database
        / "charleston"
        / "output"
        / "simulations"
        / "current_test_set_no_measures"
        / "event_0001"
        / "overland"
        / "sfincs_map.nc"
    )
    zs_file2 = (
        test_database
        / "charleston"
        / "output"
        / "simulations"
        / "current_test_set_no_measures"
        / "event_0039"
        / "overland"
        / "sfincs_map.nc"
    )
    zs_file3 = (
        test_database
        / "charleston"
        / "output"
        / "simulations"
        / "current_test_set_no_measures"
        / "event_0078"
        / "overland"
        / "sfincs_map.nc"
    )
    assert zs_file1.is_file()
    assert zs_file2.is_file()
    assert zs_file3.is_file()

    zs1 = xr.open_dataset(zs_file1).load()
    zs2 = xr.open_dataset(zs_file2).load()
    zs3 = xr.open_dataset(zs_file3).load()
    zsrp = xr.open_dataset(nc_file).load()

    fig, ax = plt.subplots(4, 2, figsize=(12, 18))

    ax[0, 0].pcolor(zs1.x, zs1.y, zs1.zsmax.squeeze(), vmin=0, vmax=2)
    ax[1, 0].pcolor(zs2.x, zs2.y, zs2.zsmax.squeeze(), vmin=0, vmax=2)
    ax[2, 0].pcolor(zs3.x, zs3.y, zs3.zsmax.squeeze(), vmin=0, vmax=2)
    ax[0, 1].pcolor(zs1.x, zs1.y, zsrp.to_array().sel(rp=1).squeeze(), vmin=0, vmax=2)
    ax[1, 1].pcolor(zs2.x, zs2.y, zsrp.to_array().sel(rp=5).squeeze(), vmin=0, vmax=2)
    ax[2, 1].pcolor(zs3.x, zs3.y, zsrp.to_array().sel(rp=50).squeeze(), vmin=0, vmax=2)
    ax[3, 0].pcolor(zs3.x, zs3.y, zsrp.to_array().sel(rp=10).squeeze(), vmin=0, vmax=2)
    ax[0, 0].set_title("event_0001")
    ax[1, 0].set_title("event_0039")
    ax[2, 0].set_title("event_0078")
    ax[0, 1].set_title("RP=1")
    ax[1, 1].set_title("RP=5")
    ax[2, 1].set_title("RP=50")
    ax[3, 1].set_title("RP=10")
    fn = (
        test_database
        / "charleston"
        / "output"
        / "simulations"
        / "current_test_set_no_measures"
        / "floodmaps.png"
    )
    plt.savefig(fn, bbox_inches="tight", dpi=225)

### Current behaviour

Floodmaps for each return period look the same

### Desired behaviour

floodmaps differ per return period, depending on event set

### Task list

- [ ] check step 1a, zs and freq matrix
- [ ] check step 1b sorted freq and zs matrix
- [ ] check step 1c, exceedance probability matrix
- [ ] check step 1d return period matrix
- [ ] check matrix "h" and valid cells
- [ ] check column-wise interpolation
- [x] check concatenation of rp flood maps

**Comment by GundulaW** [comment]
Solved, had to unstack the RP floodmaps before concatenating them
