### ISSUE TITLE
discharge shape and timeseries functionality

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#141]
### Kind of request

Adding new functionality

### Enhancement Description

add functionality for  timeseries and shape

### Task list

in def generate_dis_ts in Event class add:
- [ ] river.source == "timeseries"
- [ ] river.source == "shape"
- [ ] fix def add_dis_ts
