### ISSUE TITLE
add rainfall and river discharge plots

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#142]
### Kind of request

Changing existing functionality

### Enhancement Description

add option timeseries from csv file for wind

### Task list

in Hazard class add following options:
- [x] wind.source ="timeseries"
- [x] discharge sources = shape
- [x] discharge sources = timeseries
- [x] add tests for new wind and river options
- [ ] check wind and river options in GUI
- [ ] add rainfall plotting in back-end
- [ ] add discharge plotting in back-end
- [ ] add buttons for plotting in front-end

![6f35016c-7265-46a5-aa23-23d438becae9](https://github.com/Deltares/FloodAdapt/assets/74292006/aaed04d8-d8c4-438c-be61-084b1f0481ed)
