### ISSUE TITLE
Infographic completion backend

### ISSUE THREAD

**Issue by dladrichem** [Deltares/FloodAdapt#145]
### Kind of request

Adding new functionality

### Enhancement Description

In order for the infographic to run, the backend needs to be fixed first

### Task list

- [x] Implement fiat_toolbox metrics writer
- [x] Create infographic script
- [x] Unit test
- [x] Test with GUI
