### ISSUE TITLE
Flood-Adapt logger

### ISSUE THREAD

**Issue by dladrichem** [Deltares/FloodAdapt#146]
### Kind of request

Adding new functionality

### Enhancement Description

For as far as I could see, there is not much logging in the flood adapt repo. As a programmer, it would be handy to be able to add logging with different levels of relevance 

### Task list

- [ ] Add main logger script
- [ ] Make logger callable from all files
- [ ] Fix logging todo's
- [ ] Add unit tests
