### ISSUE TITLE
fix  issue request names

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#149]
### HydroMT version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of HydroMT.

### Reproducible Example

N/A

### Current behaviour

Forms included hydromt names

### Desired behaviour

Use correct names

### Task list

- [ ] Correct issue forms
