### ISSUE TITLE
correct pydantic version

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#151]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

N/A

### Current behaviour

pydantic v2 release is currently not compatible with FloodAdapt. 

### Desired behaviour

For fix pydantic version to 1.10.9, but in the future make floodadapt comaptible with v2

### Task list

- [ ] change pydnatic version in environmnet.yml
- [ ] change pydantic version in pyproject.toml
