### ISSUE TITLE
wrong x and y coordinates in rp_flood_maps.nc

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#153]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

  1D x and y coordinates

### Current behaviour

1D x and y coordinates

### Desired behaviour

2D x and y coordinates

### Task list

- [ ] adjust calculate_rp_floodmap function in hazard.py
