### ISSUE TITLE
Update output api

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#154]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

N/A

### Current behaviour

current version is based on a couple of hard-coded options and needs updates.

### Desired behaviour

should be flexible enough that it can read the new type of output

### Task list

- [x] Update api methods to return correct types
- [x] Update api methods based on the new FIAT output

**Comment by GundulaW** [comment]
@panosatha Can you add some more explanation for the tasks or are you picking this up yourself? Maybe Sar and Daley can help
