### ISSUE TITLE
tests may fail if an old folder is still there

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#156]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

if a test was interrupted half way and created a folder with a strategy, scenario etc. the test will fail next time when trying to create the folder again. 

### Current behaviour

if a test was interrupted half way and created a folder with a strategy, scenario etc. the test will fail next time when trying to create the folder again. 

### Desired behaviour

if a test was interrupted half way and already created a folder with a strategy, scenario etc. this folder should be deleted the next time this test is run

### Task list

- [ ] check which tests may be affected (the ones that create new strategies, measures, projections, events or scenarios

- [ ] include in every affected test an if statement to remove any old folders, for example:

    if database.input_path.joinpath("strategies", test_dict["name"]).is_dir():
        shutil.rmtree(database.input_path.joinpath("strategies", test_dict["name"]))

**Comment by GundulaW** [comment]
@tim-d-w  did you add the removal of the simulations folder to the SFINCS adapter? Then we can close this issue
