### ISSUE TITLE
system not able to handle sites with none or multiple rivers

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#157]
### Kind of request

Changing existing functionality

### Enhancement Description

FloodAdapt is written to expect exactly one river, like in Charleston. We need to ensure that it can handle none or a list or rivers

### Task list

- [x] create tests to read site file with none or multiple rivers and check how these are read in in the dictionary
- [ ] add functionality to deal with none or multiple rivers in hazard function to add discharge
- [ ] add functionality to deal with none or multiple rivers in discharge plot function (if this issue has been already handled)
- [ ] check front-end still works
- [ ] create tests with none or multiple rivers
