### ISSUE TITLE
add tests for unit conversion

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#160]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Wind in m/s should be converted to same value but it is almost double

### Current behaviour

Wind in m/s should be converted to same value but it is almost double

### Desired behaviour

Wind in m/s should be converted to same value

### Task list

- [ ] add tests for all unit conversions

**Comment by GundulaW** [comment]
at a first glance this only seems to be the case for velocity but good to check them all

**Comment by kathrynroscoe** [comment]
this falls under issue 183 (adding unit tests)
