### ISSUE TITLE
Meteo maps for offshore model only downloaded when wind_source == map

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#161]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Historical offshore only downloads meteo data when wind source is set to map. 

### Current behaviour

Historical offshore only downloads meteo data when wind source is set to map.

also producing error in in hazard: ds = ds.rename({"barometric_pressure": "press"})

### Desired behaviour

Historical offshore should always download meteo data for the offshore model, the wind and rainfall source options should only be applied in the overland model

### Task list

- [x] add additional criterion to download meteo for offshore type templates so it is always performed
- [x] change download location to output\meteo (see for more details #159 )
- [x] fix errors when running offshore model

**Comment by GundulaW** [comment]
SOLVED in https://github.com/Deltares/FloodAdapt/pull/163
