### ISSUE TITLE
Increased rainfall and storm frequency in risk mode

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#169]
### Kind of request

Adding new functionality

### Enhancement Description

Add increased rainfall and storm frequency in risk mode

### Task list

- [x] check if edit boxes are provided in GUI
- [x] check pydantic model of physical projection

change rainfall in sfincs pre-processing (similar to addition of SLR)

- [x] constant (projection only)
- [x] shape(projection only)
- [x] timeseries (event and projection)
- [x] map (event and projection)

- [x] change frequency in rp_floodmap_calculation
- [x] add tests

**Comment by GundulaW** [comment]
basically done, just needs to be merged
