### ISSUE TITLE
Not reading historic nearshore events

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#178]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Not reading historic nearshore events

### Current behaviour

Not reading historic nearshore events

### Desired behaviour

reading historic nearshore events

### Task list

- [ ] remove the added column in plot water levels

**Comment by GundulaW** [comment]
Fixed and merged
