### ISSUE TITLE
wrong SLR calculations

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#186]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

wrong SLR calculations

### Current behaviour

wrong SLR calculations: error is not constant

### Desired behaviour

correct SLR calculations

### Task list

- [ ] check wl offset
- [ ] check unit conversion

**Comment by GundulaW** [comment]
finished. Calculation was right (including the SLR up until the reference year). But in the plot I did not subtract the SLR up until the reference year, hence the interpolated value and plot were inconsistent. I fixed the plot now to make it consistent.
