### ISSUE TITLE
Change infographic and infometric folder structure

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#201]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

see current database

### Current behaviour

The database is assuming that the infographic config files are in the input folders. 

Additionally, the infometrics and infographics are saved in two folders in the output, without saving a scenario based folder.

### Desired behaviour

The infographic config info should be in the static/template folder.

The infographic and infometric output should be located in the respective scenario folder in the results.

### Task list

- [x] Update fiat_toolbox to not assume the old floodadapt folder structure
- [x] Update floodadapt to the new folder structure
