### ISSUE TITLE
GreenInfra measures not added to hazard_strategy

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#203]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

GreenInfra measures not added to hazard_strategy.

It looks like no_measures strategy and scenario without measures is re-used

### Current behaviour

GreenInfra measures not added to hazard_strategy

### Desired behaviour

GreenInfra in hazard strategy

### Task list

- [x] add test to read in strategy with green infra measures
- [x] add test to initialize scenario with green infra
- [x] add test to compare scenario with and without green infra measures

**Comment by kathrynroscoe** [comment]
This has been solved

**Comment by GundulaW** [comment]
Added tests, behaviour did not occur again. Fixed some other small bugs
