### ISSUE TITLE
Save timeseries files in metric units

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#205]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Timeseries files are currently saved in whatever metrics they are provided in.

### Current behaviour

Timeseries files are currently saved in whatever metrics they are provided in.

### Desired behaviour

Assume timeseries files contain data in gui_default_units. Do unit conversion in the backend when saving the dataframe as csv file

### Task list

- [ ] in database.write_to_csv do unit conversion from gui units to metric units before saving
- [ ] make issue to use any unit, which is passed through the frontend
