### ISSUE TITLE
Improve input/output folder structure

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares/FloodAdapt#220]
### Kind of request

Changing existing functionality

### Enhancement Description

The input and output folders would benefit from better organization from an end-user perspective. 

Here is an overview of the proposed folder structure:
![image](https://github.com/Deltares/FloodAdapt/assets/79269966/ef5decc1-6ebc-4266-8aa3-a18fd45fe6a4)
 

### Task list

- [x] * Move infographic folder to templates
- [x] * Move probabilistic folder to events --> this folder was obsolete and had already been deleted before (GW)
- [x] * Create a site configuration file item to allow a user to save SFINCS simulations or modified Delft-FIAT models. Default should be not to save these
- [x] * Move floodmap TIF files into the folder output/scenario/Flooding and give the name indicated in the image by the enhancement description
- [x] * Move Delft-FIAT output (CSV and geopackages) into the folder output/scenario/Impacts and give them the names indicated in the image by the enhancement decription
- [x] * Move the infometrics files and infographic into the folder output/scenario and give them the names indicated in the image by the enhancement description
- [x] * Add a log flie to the folder output/scenario
- [ ] copy sfincs results from existing scenario if the hazard is the same, see https://github.com/Deltares/FloodAdapt/issues/241
- [x] Move SFINCS simulation folder

NOTE:
* the names "RiskScenario1 and EventScenario1" would be the specific scenario names that the user chooses in the GUI
* For the risk scenario, there is not option to save the simulations because the floodmaps are composite maps that don't represent a single scenario.

**Comment by GundulaW** [comment]
I have added the attributes results_dir (output\Scenarios\"Scnenario_name") to Scenario and DirectImpact classes and the results_dir (output\Scenarios\"Scnenario_name"\Flooding) to the Hazard class. SFINCS output is now written to the hazard.results_dir folder.

A note on the SFINCS simulation folder: HydroMT-SFINCS can only read the SFINCS netcdf results when it has a complete SFINCS folder. And hydromt-fiat is using hydromt-sfincs to read the sfincs results!!! So we should keep the SFINCS folder at least until FIAT is finished. If we need to read the SFINCS netcdf results again at a later stage, we could always recreate the sfincs folder again from the SFINCS template folder. 

I am not deleting the SFINCS results yet. I am also running into the issue that there is a hydromt log file inside the folder, which is still in use when running a scenario and cannot be deleted.

**Comment by GundulaW** [comment]
@kathrynroscoe , what do you mean by the simulation folder is only created when the user wants them to be saved? We have to make at least temporary simulation folders somewhere. Do we delete them here if the user does not want to save them? Or shall we make temporary folder elsewhere and copy them here if the user wants to save them (that seems a little overcomplicated)

**Comment by kathrynroscoe** [comment]
There was a mistake in the picture. The naming convention should be [filetype]_[scenario-name], but this was backwards for the risk return period flood maps. Here is a revised picture. 

![image](https://github.com/Deltares/FloodAdapt/assets/79269966/b94b0fd8-4a37-4b93-b32f-c16308bad858)

**Comment by GundulaW** [comment]
I moved the sfincs simulation folder
