### ISSUE TITLE
cannot create output meteo when that already exists

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#224]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

trying to download files for he same timeframe again

### Current behaviour

not able to write in the same meteo folder

### Desired behaviour

 check if folder already exists

### Task list

- [ ] check if folder already exists

**Comment by GundulaW** [comment]
fixed in https://github.com/Deltares/FloodAdapt/pull/215

**Comment by GundulaW** [comment]
could not be replicated
