### ISSUE TITLE
historical_offshore not able to preprocess offshore sfincs model

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#227]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Running historical_offshore event cannot create sfincs offshore model

### Current behaviour

hydroMT cannot handle datasets with multiple variables, getting error in sfincs adapter in self.sf_model.setup_wind_forcing_from_grid(wind=ds)

related to known HydroMT bug: 
https://github.com/Deltares/hydromt_sfincs/issues/122 

### Desired behaviour

make a work around and parse dataArray or DataSet only containing pressure

### Task list

- [x] in hazard.py parse dataset with only pressure data
