### ISSUE TITLE
Optimize use of BFE

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#230]
### Kind of request

Changing existing functionality

### Enhancement Description

Currently is is assumed that the BFE map is saved as a geojson file with the field bfe in the static/bfe/ folder.

- There should be a site.toml attribute defining the file (so it can be any type of file) and the name of the column that has the BFE value.
- Additionally, there should be an option to provide a csv file instead where each FIAT object is already associated with a BFE. This way we can avoid the time consuming spatial join every time with do an elevate measure. (This needs to be implemented in HydroMT-FIAT)

### Task list

- [x] Change Site Model
- [x] Change files
- [x] Implement Hydromt-FIAT function to read csv directly
- [x] Change FIAT-Adapter accordingly
