### ISSUE TITLE
copy sfincs results if it has been run for another scenario with the same hazard

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#241]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

recognizing that the same hazard has been run already but rerunning it again

### Current behaviour

When running a scenario the Terminal says that simulation is reused but sfincs is run again

### Desired behaviour

copy sfincs results from the other scenario to current scenario

### Task list

- [ ] in check if hazard has already been run add a copy function
- [ ] skip re-running hazard in DirectImpacts.run()

**Comment by kathrynroscoe** [comment]
done
