### ISSUE TITLE
water level offset

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#245]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

  not applying water level offset correctly

### Current behaviour

not applying water level offset correctly

### Desired behaviour

applying water level offset correctly

### Task list

- [x] We are going to update the offset to only apply to hurricanes and offshore events, remove from synthetic
- [x] MSL to NAVD88 correction for time series
- [x] Change GUI template for synthetic to have configurable reference level, and display this reference level name (e.g. ft + MLLW)
- [x] Adjust plotting function to plot against reference level
