### ISSUE TITLE
synthetic water level

### ISSUE THREAD

**Issue by GundulaW** [Deltares/FloodAdapt#251]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

wrong

### Current behaviour

wrong

### Desired behaviour

right

### Task list

- [ ] check duration of surge

**Comment by GundulaW** [comment]
closed with PR https://github.com/Deltares/FloodAdapt/pull/246/
