### ISSUE TITLE
elevate buildings with datum ref 

### ISSUE THREAD

**Issue by panosatha** [Deltares/FloodAdapt#267]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

When running a scenario with a measure of elevating buildings with datum reference, there is an error:
local variable 'path_ref' referenced before assignment

### Current behaviour

Currently the path_ref variable which is passed to hydromt_fiat was only defined for the floodmap reference.

### Desired behaviour

A path_ref=None should be defined in case of datum reference.

### Task list

- [x] correct part of fiat_adapter code
- [x] write test for elevate with datum reference measure example
- [x] correct hydromt_fiat part
